networks:
  redis-privatenet:
    driver: bridge

volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    command: redis-server
    networks:
      - redis-privatenet
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

